### ISSUE TITLE
A question of the args "--grad_ac_step"

### ISSUE THREAD

**Issue by Kyfafyd** [QData/C-Tran#11]
Dear author,

Thanks very much for your interesting work!
I wonder why the args "--grad_ac_step" is set as 2 for VOC2007?

From your code, I see that if you set "--grad_ac_step" as 2, a minibatch images (16 images) will not be used for optimization.
Can you help me solve this issue?

Thanks very much!

**Comment by jacklanchantin** [comment]
If you use a batch size of 16, but let the gradients accumulate for 2 batches (grad_ac_step = 2), then it uses an effective batch size of 32. It helps when you can't store all 32 images in GPU memory

**Comment by Kyfafyd** [comment]
Dear author,

Thanks very much for you response!! I am clear now.
I have another question: which type and how many gpus are you used for training on COCO and VOC?

**Comment by jacklanchantin** [comment]
We used four NVIDIA Titan X GPUs

**Comment by Kyfafyd** [comment]
Dear author,

Thanks very much for you patience!
How long it will take for COCO and VOC, respectively?

**Comment by jacklanchantin** [comment]
VOC: ~5 minutes per epoch
COCO: ~1 hour per epoch

**Comment by Kyfafyd** [comment]
But it seems the default training config is 100epochs, so when the model will be converged, especially for COCO? Until 100 epochs?

**Comment by jacklanchantin** [comment]
It's possible it could take that long. you will have to run it for at least
a few days.

**Comment by Kyfafyd** [comment]
So, have you used 4 GPUs with a batch size 16? It seems 4 GPUs is capable for a batch size 32.

**Comment by jacklanchantin** [comment]
Yes, you could do that

**Comment by Kyfafyd** [comment]
Thanks very much for your response!

**Comment by THUeeY** [comment]
Excuse me, did you get the mAP of voc 2007? It was not mentioned in the paper.

**Comment by THUeeY** [comment]
> Thanks very much for your response!
Excuse me, did you get the mAP of voc 2007? It was not mentioned in the paper.

**Comment by jacklanchantin** [comment]
We did not run experiments on voc 2007 as it is a small dataset with very few labels.
