### ISSUE TITLE
A question about argument "--pos_emb" and a possible comparsive method.

### ISSUE THREAD

**Issue by Kyfafyd** [QData/C-Tran#12]
Dear author,

Thanks for your time!

I have noticed that their is an argument "--pos_emb", so how to use it, If it will improve performance?
I found if I call it when training, it will raise an error.

Meanwhile, I wonder if this AAAI2021 paper can be compared with your paper? It seems these two papers are using the same setting.
https://ojs.aaai.org/index.php/AAAI/article/view/17098/16905

**Comment by jacklanchantin** [comment]
--pos_emb is a binary flag to use the positional encoding. It will not help much

It looks like that paper came out after ours, so we did not compare
