### ISSUE TITLE
coco datasets

### ISSUE THREAD

**Issue by ly-pear** [QData/C-Tran#27]
train_data_name = 'train.data'
val_data_name = 'val_test.data'
May I ask if you can provide 'train. data' and 'val_test. data'？

**Comment by jacklanchantin** [comment]
These should be located here: [https://www.cs.virginia.edu/yanjun/jack/vision/coco.tar.gz](https://www.cs.virginia.edu/yanjun/jack/vision/coco.tar.gz)
