### ISSUE TITLE
Could you provide the label name of the VG500 subset and the download link of the dataset?

### ISSUE THREAD

**Issue by mymuli** [QData/C-Tran#4]
Thanks for sharing the code!
Could you provide the label name of the VG500 subset and the download link of the dataset?

**Comment by jacklanchantin** [comment]
Images: http://www.cs.virginia.edu/~jjl5sw/data/vision/VG500.tar.gz
Labels: http://www.cs.virginia.edu/~jjl5sw/data/vision/VG500_labels.tar.gz

**Comment by mymuli** [comment]
Thank you!

**Comment by weirukai** [comment]
where can i find the vocabulary of the labels in VG500，i am gonna try word embedding？

**Comment by jacklanchantin** [comment]
@weirukai it's the top 500 labels from the visual genome dataset: https://visualgenome.org/data_analysis/statistics

**Comment by THUeeY** [comment]
Thank you for sharing. But the download link is not accessible. Could you please update the link. Thank you very much. @jacklanchantin

**Comment by jacklanchantin** [comment]
Hi @THUeeY I'm working on getting the data back. My university department removed my home directory.

**Comment by jacklanchantin** [comment]
The links are updated in the readme. VG500 data is here:

Images: https://www.cs.virginia.edu/yanjun/jack/vision/VG500.tar.gz
Labels: https://www.cs.virginia.edu/yanjun/jack/vision/VG500_labels.tar.gz

**Comment by THUeeY** [comment]
Thank you very much!!
