### ISSUE TITLE
Unable to determine the device handle for GPU 

### ISSUE THREAD

**Issue by ZJX-CV** [QData/C-Tran#6]
system can not find GPU devices.... is there something wrong with the code？

**Comment by jacklanchantin** [comment]
What kind of GPU are you using. I haven't run into this issue.

**Comment by alleniver** [comment]
i get the error:AssertionError: Torch not compiled with CUDA enabled

**Comment by alleniver** [comment]
i got the error:AssertionError: Torch not compiled with CUDA enabled
